In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE
import lightgbm as lgb

In [3]:
# Load the dataset
df = pd.read_csv('patients.csv')

#quick info
print(df.info())

print(df.describe())

print(df.isnull().sum())

print(df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PatientId       110527 non-null  float64
 1   AppointmentID   110527 non-null  int64
 2   Gender          110527 non-null  object
 3   ScheduledDay    110527 non-null  object
 4   AppointmentDay  110527 non-null  object
 5   Age             110527 non-null  int64
 6   Neighbourhood   110527 non-null  object
 7   Scholarship     110527 non-null  int64
 8   Hipertension    110527 non-null  int64
 9   Diabetes        110527 non-null  int64
 10  Alcoholism      110527 non-null  int64
 11  Handcap         110527 non-null  int64
 12  SMS_received    110527 non-null  int64
 13  No-show         110527 non-null  object
dtypes: float64(1), int64(8), object(5)
memory usage: 11.8+ MB
None
          PatientId  AppointmentID            Age    Scholarship  \
count  1.105270e+05   1.105270e+05  110527.000000  110527.000000
mean   1.474963e+14   5.675305e+06      37.088874       0.098266
std    2.560949e+14   7.129575e+04      23.110205       0.297675
min    3.921784e+04   5.030230e+06      -1.000000       0.000000
25%    4.172614e+12   5.640286e+06      18.000000       0.000000
50%    3.173184e+13   5.680573e+06      37.000000       0.000000
75%    9.439172e+13   5.725524e+06      55.000000       0.000000
max    9.999816e+14   5.790484e+06     115.000000       1.000000

        Hipertension       Diabetes     Alcoholism        Handcap  \
count  110527.000000  110527.000000  110527.000000  110527.000000
mean        0.197246       0.071865       0.030400       0.022248
std         0.397921       0.258265       0.171686       0.161543
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%         0.000000       0.000000       0.000000       0.000000
max         1.000000       1.000000       1.000000       4.000000

        SMS_received
count  110527.000000
mean        0.321026
std         0.466873
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         1.000000
PatientId         0
AppointmentID     0
Gender            0
ScheduledDay      0
AppointmentDay    0
Age               0
Neighbourhood     0
Scholarship       0
Hipertension      0
Diabetes          0
Alcoholism        0
Handcap           0
SMS_received      0
No-show           0
dtype: int64
0

## Data cleaning and preprocessing

### Subtask:
Handle the negative age value, convert date columns to datetime objects, and extract relevant features like waiting time.

**Reasoning**:
Handle the negative age value, convert date columns to datetime objects, and extract relevant features like waiting time as per the instructions.

In [4]:
# Remove rows with negative age
df = df[df['Age'] >= 0]

# Convert date columns to datetime objects
df['ScheduledDay'] = pd.to_datetime(df['ScheduledDay']).dt.tz_convert(None)
df['AppointmentDay'] = pd.to_datetime(df['AppointmentDay']).dt.tz_convert(None)

# Calculate waiting time
df['WaitingTime'] = (df['AppointmentDay'] - df['ScheduledDay']).dt.days

# Display the first few rows and info of the updated dataframe
display(df.head())
print(df.info())

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show,WaitingTime
0,2.987250e+13,5642903,F,2016-04-29 18:38:08,2016-04-29,62,JARDIM DA PENHA,0,1,0,0,0,0,No,-1
1,5.589978e+14,5642503,M,2016-04-29 16:08:27,2016-04-29,56,JARDIM DA PENHA,0,0,0,0,0,0,No,-1
2,4.262962e+12,5642549,F,2016-04-29 16:19:04,2016-04-29,62,MATA DA PRAIA,0,0,0,0,0,0,No,-1
3,8.679512e+11,5642828,F,2016-04-29 17:29:31,2016-04-29,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No,-1
4,8.841186e+12,5642494,F,2016-04-29 16:07:23,2016-04-29,56,JARDIM DA PENHA,0,1,1,0,0,0,No,-1

<class 'pandas.core.frame.DataFrame'>
Index: 110526 entries, 0 to 110526
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PatientId       110526 non-null  float64
 1   AppointmentID   110526 non-null  int64
 2   Gender          110526 non-null  object
 3   ScheduledDay    110526 non-null  datetime64[ns]
 4   AppointmentDay  110526 non-null  datetime64[ns]
 5   Age             110526 non-null  int64
 6   Neighbourhood   110526 non-null  object
 7   Scholarship     110526 non-null  int64
 8   Hipertension    110526 non-null  int64
 9   Diabetes        110526 non-null  int64
 10  Alcoholism      110526 non-null  int64
 11  Handcap         110526 non-null  int64
 12  SMS_received    110526 non-null  int64
 13  No-show         110526 non-null  object
 14  WaitingTime     110526 non-null  int64
dtypes: datetime64[ns](2), float64(1), int64(9), object(3)
memory usage: 13.5+ MB
None

## Feature engineering

### Subtask:
Create new features that could be relevant for predicting no-shows, such as the day of the week of the appointment, and the time difference between scheduling and appointment. Also, consider encoding categorical variables.

**Reasoning**:
Extract features from date columns, encode categorical features, and convert the target variable.

In [5]:
# Extract day of the week from AppointmentDay
df['AppointmentDayOfWeek'] = df['AppointmentDay'].dt.dayofweek

# Extract hour of the day from ScheduledDay
df['ScheduledHour'] = df['ScheduledDay'].dt.hour

# Convert Gender to numerical using one-hot encoding
df = pd.get_dummies(df, columns=['Gender'], drop_first=True)

# Convert Neighbourhood to numerical using one-hot encoding
df = pd.get_dummies(df, columns=['Neighbourhood'])

# Convert 'No-show' to binary
df['No-show'] = df['No-show'].apply(lambda x: 1 if x == 'Yes' else 0)

# Display the first few rows and info of the updated dataframe
display(df.head())
print(df.info())

,PatientId,AppointmentID,ScheduledDay,AppointmentDay,Age,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,...,Neighbourhood_SANTOS REIS,Neighbourhood_SEGURANÇA DO LAR,Neighbourhood_SOLON BORGES,Neighbourhood_SÃO BENEDITO,Neighbourhood_SÃO CRISTÓVÃO,Neighbourhood_SÃO JOSÉ,Neighbourhood_SÃO PEDRO,Neighbourhood_TABUAZEIRO,Neighbourhood_UNIVERSITÁRIO,Neighbourhood_VILA RUBIM
0,2.987250e+13,5642903,2016-04-29 18:38:08,2016-04-29,62,0,1,0,0,0,...,False,False,False,False,False,False,False,False,False,False
1,5.589978e+14,5642503,2016-04-29 16:08:27,2016-04-29,56,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
2,4.262962e+12,5642549,2016-04-29 16:19:04,2016-04-29,62,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
3,8.679512e+11,5642828,2016-04-29 17:29:31,2016-04-29,8,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
4,8.841186e+12,5642494,2016-04-29 16:07:23,2016-04-29,56,0,1,1,0,0,...,False,False,False,False,False,False,False,False,False,False

<class 'pandas.core.frame.DataFrame'>
Index: 110526 entries, 0 to 110526
Data columns (total 97 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   PatientId                                  110526 non-null  float64
 1   AppointmentID                              110526 non-null  int64
 2   ScheduledDay                               110526 non-null  datetime64[ns]
 3   AppointmentDay                             110526 non-null  datetime64[ns]
 4   Age                                        110526 non-null  int64
 5   Scholarship                                110526 non-null  int64
 6   Hipertension                               110526 non-null  int64
 7   Diabetes                                   110526 non-null  int64
 8   Alcoholism                                 110526 non-null  int64
 9   Handcap                                    110526 non-null  int64
 10  SMS_received                               110526 non-null  int64
 11  No-show                                    110526 non-null  int64
 12  WaitingTime                                110526 non-null  int64
 13  AppointmentDayOfWeek                       110526 non-null  int32
 14  ScheduledHour                              110526 non-null  int32
 15  Gender_M                                   110526 non-null  bool
 16  Neighbourhood_AEROPORTO                    110526 non-null  bool
 17  Neighbourhood_ANDORINHAS                   110526 non-null  bool
 18  Neighbourhood_ANTÔNIO HONÓRIO              110526 non-null  bool
 19  Neighbourhood_ARIOVALDO FAVALESSA          110526 non-null  bool
 20  Neighbourhood_BARRO VERMELHO               110526 non-null  bool
 21  Neighbourhood_BELA VISTA                   110526 non-null  bool
 22  Neighbourhood_BENTO FERREIRA               110526 non-null  bool
 23  Neighbourhood_BOA VISTA                    110526 non-null  bool
 24  Neighbourhood_BONFIM                       110526 non-null  bool
 25  Neighbourhood_CARATOÍRA                    110526 non-null  bool
 26  Neighbourhood_CENTRO                       110526 non-null  bool
 27  Neighbourhood_COMDUSA                      110526 non-null  bool
 28  Neighbourhood_CONQUISTA                    110526 non-null  bool
 29  Neighbourhood_CONSOLAÇÃO                   110526 non-null  bool
 30  Neighbourhood_CRUZAMENTO                   110526 non-null  bool
 31  Neighbourhood_DA PENHA                     110526 non-null  bool
 32  Neighbourhood_DE LOURDES                   110526 non-null  bool
 33  Neighbourhood_DO CABRAL                    110526 non-null  bool
 34  Neighbourhood_DO MOSCOSO                   110526 non-null  bool
 35  Neighbourhood_DO QUADRO                    110526 non-null  bool
 36  Neighbourhood_ENSEADA DO SUÁ               110526 non-null  bool
 37  Neighbourhood_ESTRELINHA                   110526 non-null  bool
 38  Neighbourhood_FONTE GRANDE                 110526 non-null  bool
 39  Neighbourhood_FORTE SÃO JOÃO               110526 non-null  bool
 40  Neighbourhood_FRADINHOS                    110526 non-null  bool
 41  Neighbourhood_GOIABEIRAS                   110526 non-null  bool
 42  Neighbourhood_GRANDE VITÓRIA               110526 non-null  bool
 43  Neighbourhood_GURIGICA                     110526 non-null  bool
 44  Neighbourhood_HORTO                        110526 non-null  bool
 45  Neighbourhood_ILHA DAS CAIEIRAS            110526 non-null  bool
 46  Neighbourhood_ILHA DE SANTA MARIA          110526 non-null  bool
 47  Neighbourhood_ILHA DO BOI                  110526 non-null  bool
 48  Neighbourhood_ILHA DO FRADE                110526 non-null  bool
 49  Neighbourhood_ILHA DO PRÍNCIPE             110526 non-null  bool
 50  Neighbourhood_ILHAS OCEÂNICAS DE TRINDADE  110526 non-null  bool
 51  Neighbourhood_INHANGUETÁ                   110526 non-null  bool
 52  Neighbourhood_ITARARÉ                      110526 non-null  bool
 53  Neighbourhood_JABOUR                       110526 non-null  bool
 54  Neighbourhood_JARDIM CAMBURI               110526 non-null  bool
 55  Neighbourhood_JARDIM DA PENHA              110526 non-null  bool
 56  Neighbourhood_JESUS DE NAZARETH            110526 non-null  bool
 57  Neighbourhood_JOANA D´ARC                  110526 non-null  bool
 58  Neighbourhood_JUCUTUQUARA                  110526 non-null  bool
 59  Neighbourhood_MARIA ORTIZ                  110526 non-null  bool
 60  Neighbourhood_MARUÍPE                      110526 non-null  bool
 61  Neighbourhood_MATA DA PRAIA                110526 non-null  bool
 62  Neighbourhood_MONTE BELO                   110526 non-null  bool
 63  Neighbourhood_MORADA DE CAMBURI            110526 non-null  bool
 64  Neighbourhood_MÁRIO CYPRESTE               110526 non-null  bool
 65  Neighbourhood_NAZARETH                     110526 non-null  bool
 66  Neighbourhood_NOVA PALESTINA               110526 non-null  bool
 67  Neighbourhood_PARQUE INDUSTRIAL            110526 non-null  bool
 68  Neighbourhood_PARQUE MOSCOSO               110526 non-null  bool
 69  Neighbourhood_PIEDADE                      110526 non-null  bool
 70  Neighbourhood_PONTAL DE CAMBURI            110526 non-null  bool
 71  Neighbourhood_PRAIA DO CANTO               110526 non-null  bool
 72  Neighbourhood_PRAIA DO SUÁ                 110526 non-null  bool
 73  Neighbourhood_REDENÇÃO                     110526 non-null  bool
 74  Neighbourhood_REPÚBLICA                    110526 non-null  bool
 75  Neighbourhood_RESISTÊNCIA                  110526 non-null  bool
 76  Neighbourhood_ROMÃO                        110526 non-null  bool
 77  Neighbourhood_SANTA CECÍLIA                110526 non-null  bool
 78  Neighbourhood_SANTA CLARA                  110526 non-null  bool
 79  Neighbourhood_SANTA HELENA                 110526 non-null  bool
 80  Neighbourhood_SANTA LUÍZA                  110526 non-null  bool
 81  Neighbourhood_SANTA LÚCIA                  110526 non-null  bool
 82  Neighbourhood_SANTA MARTHA                 110526 non-null  bool
 83  Neighbourhood_SANTA TEREZA                 110526 non-null  bool
 84  Neighbourhood_SANTO ANDRÉ                  110526 non-null  bool
 85  Neighbourhood_SANTO ANTÔNIO                110526 non-null  bool
 86  Neighbourhood_SANTOS DUMONT                110526 non-null  bool
 87  Neighbourhood_SANTOS REIS                  110526 non-null  bool
 88  Neighbourhood_SEGURANÇA DO LAR             110526 non-null  bool
 89  Neighbourhood_SOLON BORGES                 110526 non-null  bool
 90  Neighbourhood_SÃO BENEDITO                 110526 non-null  bool
 91  Neighbourhood_SÃO CRISTÓVÃO                110526 non-null  bool
 92  Neighbourhood_SÃO JOSÉ                     110526 non-null  bool
 93  Neighbourhood_SÃO PEDRO                    110526 non-null  bool
 94  Neighbourhood_TABUAZEIRO                   110526 non-null  bool
 95  Neighbourhood_UNIVERSITÁRIO                110526 non-null  bool
 96  Neighbourhood_VILA RUBIM                   110526 non-null  bool
dtypes: bool(82), datetime64[ns](2), float64(1), int32(2), int64(10)
memory usage: 21.3 MB
None

## Handle Imbalanced Data

### Subtask:
Address the class imbalance in the 'No-show' column using SMOTE.

**Reasoning**:
The dataset is imbalanced with respect to the target variable 'No-show'. Using SMOTE will help to balance the classes by oversampling the minority class.

In [6]:
# Separate features and target variable
X = df.drop('No-show', axis=1)
y = df['No-show']

# Drop non-numeric and irrelevant columns
X = X.select_dtypes(include=np.number)
X = X.drop(['PatientId', 'AppointmentID'], axis=1)


# Handle infinite values by replacing with NaN and then imputing (or dropping)
X.replace([np.inf, -np.inf], np.nan, inplace=True)
# For simplicity, we will drop rows with NaN values after replacing inf.
# A more robust approach would be imputation.
X.dropna(inplace=True)
y = y[X.index] # Ensure y aligns with X after dropping rows


# Apply SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

print("Shape of original data:", X.shape)
print("Shape of resampled data:", X_resampled.shape)
print("Value counts of original target variable:\n", y.value_counts())
print("Value counts of resampled target variable:\n", y_resampled.value_counts())

Shape of original data: (110526, 10)
Shape of resampled data: (176414, 10)
Value counts of original target variable:
 No-show
0    88207
1    22319
Name: count, dtype: int64
Value counts of resampled target variable:
 No-show
0    88207
1    88207
Name: count, dtype: int64

## Model Selection

### Subtask:
Choose appropriate models for binary classification. Given the dataset size, tree-based models like LightGBM or XGBoost are good candidates. Neural networks with TensorFlow or PyTorch could also be explored but might require more computational resources and tuning.

## Model Training and Evaluation

### Subtask:
Split the data into training and testing sets, train a LightGBM model, and evaluate its performance.

**Reasoning**:
Split the resampled data into training and testing sets to train and evaluate the LightGBM model.

In [7]:
# Split the resampled data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42, stratify=y_resampled)

# Initialize and train the LightGBM model
lgbm = lgb.LGBMClassifier(random_state=42)
lgbm.fit(X_train, y_train)

# Make predictions on the test set
y_pred = lgbm.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Classification Report:\n", report)
print("Confusion Matrix:\n", confusion)

[LightGBM] [Info] Number of positive: 70566, number of negative: 70565
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.032536 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 274
[LightGBM] [Info] Number of data points in the train set: 141131, number of used features: 10
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500004 -> initscore=0.000014
[LightGBM] [Info] Start training from score 0.000014
Accuracy: 0.7111923589263951
Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.60      0.68     17642
           1       0.67      0.82      0.74     17641

    accuracy                           0.71     35283
   macro avg       0.72      0.71      0.71     35283
weighted avg       0.72      0.71      0.71     35283

Confusion Matrix:
 [[10584  7058]
 [ 3132 14509]]

## Hyperparameter Tuning

### Subtask:
Optimize the performance of the chosen model(s) using techniques like cross-validation and grid search or random search.

**Reasoning**:
Perform hyperparameter tuning on the LightGBM model using Randomized Search with cross-validation to find better parameters and potentially improve performance.

In [8]:
from sklearn.model_selection import RandomizedSearchCV

# Define the parameter distribution for RandomizedSearchCV
param_dist = {
    'n_estimators': [100, 200, 300, 400, 500],
    'learning_rate': [0.01, 0.05, 0.1, 0.15, 0.2],
    'num_leaves': [20, 31, 40, 50],
    'max_depth': [-1, 10, 15, 20],
    'min_child_samples': [20, 30, 40, 50],
    'subsample': [0.6, 0.7, 0.8, 0.9, 1.0],
    'colsample_bytree': [0.6, 0.7, 0.8, 0.9, 1.0],
    'reg_alpha': [0, 0.1, 0.5, 1],
    'reg_lambda': [0, 0.1, 0.5, 1],
}

# Initialize RandomizedSearchCV
# n_iter controls the number of parameter combinations sampled. More is better but takes longer.
# cv is the number of cross-validation folds.
random_search = RandomizedSearchCV(lgbm, param_distributions=param_dist, n_iter=50, cv=5, scoring='f1', random_state=42, n_jobs=-1)

# Fit RandomizedSearchCV to the training data
print("Starting Randomized Search for Hyperparameter Tuning...")
random_search.fit(X_train, y_train)
print("Randomized Search finished.")

# Print the best parameters and best score
print("Best parameters found:", random_search.best_params_)
print("Best F1-score found:", random_search.best_score_)

# Get the best model
best_lgbm = random_search.best_estimator_

# Evaluate the best model on the test set
y_pred_best = best_lgbm.predict(X_test)

# Evaluate the best model
accuracy_best = accuracy_score(y_test, y_pred_best)
report_best = classification_report(y_test, y_pred_best)
confusion_best = confusion_matrix(y_test, y_pred_best)

print(f"Best Model Accuracy: {accuracy_best}")
print("Best Model Classification Report:\n", report_best)
print("Best Model Confusion Matrix:\n", confusion_best)

Starting Randomized Search for Hyperparameter Tuning...
[LightGBM] [Info] Number of positive: 70566, number of negative: 70565
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.019566 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 274
[LightGBM] [Info] Number of data points in the train set: 141131, number of used features: 10
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500004 -> initscore=0.000014
[LightGBM] [Info] Start training from score 0.000014
Randomized Search finished.
Best parameters found: {'subsample': 0.8, 'reg_lambda': 0.5, 'reg_alpha': 0.5, 'num_leaves': 40, 'n_estimators': 500, 'min_child_samples': 30, 'max_depth': -1, 'learning_rate': 0.2, 'colsample_bytree': 0.9}
Best F1-score found: 0.7592464242007881
Best Model Accuracy: 0.7387693790210583
Best Model Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.65      0.71     17642
           1       0.70      0.83      0.76     17641

    accuracy                           0.74     35283
   macro avg       0.75      0.74      0.74     35283
weighted avg       0.75      0.74      0.74     35283

Best Model Confusion Matrix:
 [[11502  6140]
 [ 3077 14564]]

## Unbiased Evaluation

### Subtask:
Ensure the model is unbiased by evaluating its performance on different subgroups of the data (e.g., by gender, age, or neighbourhood).

In [9]:
import pickle

# Save the best model to a pkl file
filename = 'best_lgbm_model_unbiased.pkl'
pickle.dump(best_lgbm, open(filename, 'wb'))

print(f"Best model saved to {filename}")

Best model saved to best_lgbm_model_unbiased.pkl